# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: "hello-devops-api"
fullname: "hello-devops-api"

labels:
  app: "hello-devops-api"
selectorLabels:
  app: "hello-devops-api"

serviceAccount:
    create: true

imagePullSecrets: 
  - name: github-secret

# hello-devops-api configuration
image:
  repository: ghcr.io/corentinbaudet/hello-devops-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: ""
  containerPort: 8080

replicaCount: 2
autoscaling:
    enabled: false

podAnnotations: {
  "helm.sh/hook": pre-install,pre-upgrade,
  "helm.sh/hook-weight": "-5",
  "helm.sh/hook-delete-policy": hook-succeeded
}

affinity: {}

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8080
