apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}-deployment
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # labels:
      #   {{- include "hello-devops-api.labels" . | nindent 8 }}
      #   {{- with .Values.podLabels }}
      #   {{- toYaml . | nindent 8 }}
      #   {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount }}-sa
      containers:
        - name: {{ .Values.fullname }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          # readinessProbe:
          #   {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          # volumeMounts:
          #   {{- toYaml . | nindent 12 }}
          # {{- end }}
      # {{- with .Values.affinity }}
      # affinity:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: hello-devops-api-deployment
# spec:
#   selector:
#     matchLabels:
#       app: hello-devops-api
#   template:
#     metadata:
#       labels:
#         app: hello-devops-api
#     spec:
#       serviceAccountName: hello-devops-api-sa
#       containers:
#       - name: hello-devops-api
#         image: ghcr.io/corentinbaudet/hello-devops-api:0.1
#         ports:
#         - containerPort: 8080