{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: {{ .Values.imagePullSecrets.name }}
metadata:
  name: {{ include "hello-devops-api.serviceAccountName" . }}
  labels:
    {{- include "hello-devops-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}

# apiVersion: v1
# kind: ServiceAccount
# imagePullSecrets:
# - name: github-secret
# metadata:
#   name: hello-devops-api-sa