{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
{{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
metadata:
  name: {{ include "Values.serviceAccount.name" . }}
  labels:
    {{- include "hello-devops-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}

# apiVersion: v1
# kind: ServiceAccount
# imagePullSecrets:
# - name: github-secret
# metadata:
#   name: hello-devops-api-sa