apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}-svc
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.selectorLabels | nindent 4 }}

# apiVersion: v1
# kind: Service
# metadata:
#   name: hello-devops-api-svc
# spec:
#   # type: NodePort
#   selector:
#     app: hello-devops-api
#   ports:
#   - protocol: TCP
#     port: 8080
#     targetPort: 8080