{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  {{- toYaml .Values.imagePullSecrets | nindent 2 }}
metadata:
  name: {{ .Values.fullname }}-sa
  labels:
    {{- toYaml .Values.selectorLabels | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
